version: "3.8"

services:

  # RabbitMQ
  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro_vehicle

  # Consul
  consul-dev:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - '8500:8500'
    command: 'agent -dev -node=vehicle -client=0.0.0.0 -log-level=INFO'
    networks:
      - micro_vehicle

  consul-importer:
    image: consul-importer:1.19.2
    depends_on:
      - consul-dev
    networks:
      - micro_vehicle

  # Gateway
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - micro_vehicle

  # Elk Stack Services

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - micro_vehicle

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044" # Filebeat port
    depends_on:
      - elasticsearch
    networks:
      - micro_vehicle

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Directly connect to Elasticsearch
      - XPACK_SECURITY_ENABLED=false  # Disable security in Kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - micro_vehicle




networks:
  micro_vehicle:
    driver: bridge