INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70001, 'Ford', 'Mustang', 1965, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70002, 'Chevrolet', 'Bel Air', 1957, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70003, 'Volkswagen', 'Beetle', 1963, 'Green');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70004, 'Porsche', '911', 1970, 'Yellow');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70005, 'BMW', '2002', 1972, 'Orange');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70006, 'Mercedes-Benz', '300SL', 1955, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70007, 'Jaguar', 'E-Type', 1961, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70008, 'Ferrari', '308 GTS', 1977, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70009, 'Pontiac', 'GTO', 1967, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70010, 'Dodge', 'Charger', 1969, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70011, 'Chevrolet', 'Corvette', 1963, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70012, 'Aston Martin', 'DB5', 1964, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70013, 'Ford', 'Thunderbird', 1955, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70014, 'Buick', 'Riviera', 1965, 'Gold');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70015, 'Plymouth', 'Barracuda', 1970, 'Orange');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70016, 'Cadillac', 'Eldorado', 1959, 'Pink');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70017, 'Alfa Romeo', 'Spider', 1966, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70018, 'Lancia', 'Stratos', 1974, 'Green');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70019, 'Fiat', '500', 1967, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70020, 'DeLorean', 'DMC-12', 1981, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70021, 'Lotus', 'Esprit', 1976, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70022, 'Mazda', 'RX-7', 1979, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70023, 'Nissan', '300ZX', 1984, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70024, 'Toyota', 'Celica', 1973, 'Yellow');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70025, 'Volvo', 'P1800', 1962, 'Green');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70026, 'Toyota', 'Camry', 2020, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70027, 'Honda', 'Civic', 2021, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70028, 'Ford', 'Mustang', 2019, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70029, 'Chevrolet', 'Malibu', 2018, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70030, 'Nissan', 'Altima', 2020, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70031, 'Tesla', 'Model S', 2022, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70032, 'BMW', 'X5', 2021, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70033, 'Audi', 'A6', 2017, 'Gray');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70034, 'Mercedes-Benz', 'C-Class', 2020, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70035, 'Kia', 'Sorento', 2021, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70036, 'Hyundai', 'Elantra', 2019, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70037, 'Mazda', 'CX-5', 2020, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70038, 'Subaru', 'Outback', 2021, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70039, 'Volkswagen', 'Passat', 2020, 'Gray');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70040, 'Volvo', 'XC90', 2018, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70041, 'Jaguar', 'XE', 2019, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70042, 'Porsche', '911', 2022, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70043, 'Ferrari', '488', 2020, 'Yellow');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70044, 'Lamborghini', 'Huracan', 2021, 'Green');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70045, 'McLaren', '720S', 2019, 'Orange');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70046, 'Ford', 'F-150', 2021, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70047, 'Chevrolet', 'Silverado', 2020, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70048, 'Toyota', 'Tundra', 2019, 'Gray');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70049, 'Ram', '1500', 2021, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70050, 'Jeep', 'Wrangler', 2022, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70051, 'Land Rover', 'Discovery', 2020, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70052, 'Tesla', 'Model 3', 2021, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70053, 'BMW', '3 Series', 2019, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70054, 'Audi', 'Q5', 2020, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70055, 'Mercedes-Benz', 'GLE', 2021, 'Gray');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70056, 'Honda', 'Accord', 2020, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70057, 'Hyundai', 'Tucson', 2019, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70058, 'Mazda', 'Mazda3', 2021, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70059, 'Subaru', 'Forester', 2020, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70060, 'Volkswagen', 'Tiguan', 2021, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70061, 'Volvo', 'S60', 2022, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70062, 'Porsche', 'Cayenne', 2020, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70063, 'Ferrari', 'Portofino', 2019, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70064, 'Lamborghini', 'Aventador', 2021, 'Yellow');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70065, 'McLaren', 'GT', 2020, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70066, 'Kia', 'Optima', 2019, 'Silver');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70067, 'Ford', 'Explorer', 2021, 'White');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70068, 'Chevrolet', 'Traverse', 2020, 'Gray');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70069, 'Nissan', 'Murano', 2019, 'Black');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70070, 'Jeep', 'Grand Cherokee', 2021, 'Red');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70071, 'Land Rover', 'Range Rover', 2020, 'Blue');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70072, 'Toyota', 'Highlander', 2021, 'Gray');
INSERT INTO Car (product_id, make, model, car_year, color) VALUES (70073, 'Honda', 'Pilot', 2019, 'Silver');
