INSERT INTO Car (make, model, car_year, color) VALUES ('Ford', 'Mustang', 1965, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Chevrolet', 'Bel Air', 1957, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Volkswagen', 'Beetle', 1963, 'Green');
INSERT INTO Car (make, model, car_year, color) VALUES ('Porsche', '911', 1970, 'Yellow');
INSERT INTO Car (make, model, car_year, color) VALUES ('BMW', '2002', 1972, 'Orange');
INSERT INTO Car (make, model, car_year, color) VALUES ('Mercedes-Benz', '300SL', 1955, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Jaguar', 'E-Type', 1961, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ferrari', '308 GTS', 1977, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Pontiac', 'GTO', 1967, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Dodge', 'Charger', 1969, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Chevrolet', 'Corvette', 1963, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Aston Martin', 'DB5', 1964, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ford', 'Thunderbird', 1955, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Buick', 'Riviera', 1965, 'Gold');
INSERT INTO Car (make, model, car_year, color) VALUES ('Plymouth', 'Barracuda', 1970, 'Orange');
INSERT INTO Car (make, model, car_year, color) VALUES ('Cadillac', 'Eldorado', 1959, 'Pink');
INSERT INTO Car (make, model, car_year, color) VALUES ('Alfa Romeo', 'Spider', 1966, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Lancia', 'Stratos', 1974, 'Green');
INSERT INTO Car (make, model, car_year, color) VALUES ('Fiat', '500', 1967, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('DeLorean', 'DMC-12', 1981, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Lotus', 'Esprit', 1976, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Mazda', 'RX-7', 1979, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Nissan', '300ZX', 1984, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Toyota', 'Celica', 1973, 'Yellow');
INSERT INTO Car (make, model, car_year, color) VALUES ('Volvo', 'P1800', 1962, 'Green');
INSERT INTO Car (make, model, car_year, color) VALUES ('Toyota', 'Camry', 2020, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Honda', 'Civic', 2021, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ford', 'Mustang', 2019, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Chevrolet', 'Malibu', 2018, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Nissan', 'Altima', 2020, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Tesla', 'Model S', 2022, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('BMW', 'X5', 2021, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Audi', 'A6', 2017, 'Gray');
INSERT INTO Car (make, model, car_year, color) VALUES ('Mercedes-Benz', 'C-Class', 2020, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Kia', 'Sorento', 2021, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Hyundai', 'Elantra', 2019, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Mazda', 'CX-5', 2020, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Subaru', 'Outback', 2021, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Volkswagen', 'Passat', 2020, 'Gray');
INSERT INTO Car (make, model, car_year, color) VALUES ('Volvo', 'XC90', 2018, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Jaguar', 'XE', 2019, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Porsche', '911', 2022, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ferrari', '488', 2020, 'Yellow');
INSERT INTO Car (make, model, car_year, color) VALUES ('Lamborghini', 'Huracan', 2021, 'Green');
INSERT INTO Car (make, model, car_year, color) VALUES ('McLaren', '720S', 2019, 'Orange');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ford', 'F-150', 2021, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Chevrolet', 'Silverado', 2020, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Toyota', 'Tundra', 2019, 'Gray');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ram', '1500', 2021, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Jeep', 'Wrangler', 2022, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Land Rover', 'Discovery', 2020, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Tesla', 'Model 3', 2021, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('BMW', '3 Series', 2019, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Audi', 'Q5', 2020, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Mercedes-Benz', 'GLE', 2021, 'Gray');
INSERT INTO Car (make, model, car_year, color) VALUES ('Honda', 'Accord', 2020, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Hyundai', 'Tucson', 2019, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Mazda', 'Mazda3', 2021, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Subaru', 'Forester', 2020, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Volkswagen', 'Tiguan', 2021, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Volvo', 'S60', 2022, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Porsche', 'Cayenne', 2020, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ferrari', 'Portofino', 2019, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Lamborghini', 'Aventador', 2021, 'Yellow');
INSERT INTO Car (make, model, car_year, color) VALUES ('McLaren', 'GT', 2020, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Kia', 'Optima', 2019, 'Silver');
INSERT INTO Car (make, model, car_year, color) VALUES ('Ford', 'Explorer', 2021, 'White');
INSERT INTO Car (make, model, car_year, color) VALUES ('Chevrolet', 'Traverse', 2020, 'Gray');
INSERT INTO Car (make, model, car_year, color) VALUES ('Nissan', 'Murano', 2019, 'Black');
INSERT INTO Car (make, model, car_year, color) VALUES ('Jeep', 'Grand Cherokee', 2021, 'Red');
INSERT INTO Car (make, model, car_year, color) VALUES ('Land Rover', 'Range Rover', 2020, 'Blue');
INSERT INTO Car (make, model, car_year, color) VALUES ('Toyota', 'Highlander', 2021, 'Gray');
INSERT INTO Car (make, model, car_year, color) VALUES ('Honda', 'Pilot', 2019, 'Silver');

